analytics: {}
color:
  brandColors:
    - '#d2d2d4'
    - '#0a2c5c'
    - '#0064a8'
    - '#506688'
    - '#9ba5b9'
  brandStrength: 0.658717
  lightness: 0.625
  rhythmicContrast: 0.490131
  saturation: 0.515625
cta: {}
layout_spectrum: 0
name: Jive Spider
opengraph: {}
purpose: []
typography_spectrum: 0.611842
