name: Jive Spider
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4674868294969201
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.28093998483382165
  lightness: 0.027488840743899345
  saturation: 0.7521538422442973
  rhythmicContrast: 0.18242754274979234
purpose: []
