name: Jive Spider
favicon: null
layout_spectrum: 0
typography_spectrum: 0.08328
title: Jivespider
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#825444'
    - '#422924'
    - '#e3913f'
    - '#ffe745'
  brandStrength: 0.658717
  lightness: 0.625
  saturation: 0.515625
  rhythmicContrast: 0.490131
purpose: []
