name: Jive Spider
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4674868294969201
title: JiveSpider
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6fbf5'
    - '#17181d'
    - '#a8afb9'
    - '#5e222c'
    - '#8d9089'
  brandStrength: 0
  lightness: 0.027488840743899345
  saturation: 0.7521538422442973
  rhythmicContrast: 0.18242754274979234
purpose: []
