name: Jive Spider
favicon: null
layout_spectrum: 0.75233
typography_spectrum: 0.5
title: JiveSpider
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6fbf5'
    - '#17181d'
    - '#a8afb9'
    - '#5e222c'
    - '#8d9089'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
